apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  ports:
    - name: grpc
      port: 9000
  selector:
    app: backend-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  labels:
    app: backend-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
      version: v1
  template:
    metadata:
      labels:
        app: backend-service
        version: v1
    spec:
      serviceAccountName: backend-service
      containers:
        - name: backend-service
          image: <repo>/backend-service:<version>
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          securityContext:
            runAsUser: 1000
---